# Problem 12: Highly divisible triangular number
#
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred divisors?

library(projecteulerr)

n_factors <- function(n) length(get_factors(n))

wayTooManyTriangularNumbers = get_triangular_numbers(5*10^4)
counter = 1
triNum = wayTooManyTriangularNumbers[counter]
while(n_factors(iTriNum) < 500){
    counter = counter + 1
    iTriNum = wayTooManyTriangularNumbers[counter]
}
triNum

