# Problem 44: Pentagon numbers
#
# Pentagonal numbers are generated by the formula, P_n=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal and D = |P_k − P_j| is minimized; what is the value of D?

library(projecteulerr)

max(which((get_pentagonal_numbers(100) %>% diff()) <= 48))

MAX_N = 15
pents = get_pentagonal_numbers(MAX_N)
pentSums = rowSums(expand.grid(pentagonals, pentagonals))
isSumPent = sapply(pentSums, is_polygonal_number, s = 5)
pentDiffs = rowSums(expand.grid(pentagonals, -pentagonals))
pentDiffs
isDiffPent = sapply(pentDiffs, is_polygonal_number, s = 5)


